#!/bin/sh
echo Stopping ALL containers...
docker stop $(docker ps -a -q)
echo Deleting ALL containers...
docker rm $(docker ps -a -q)
echo Deleting dangling images...
docker rmi $(docker images -a --filter=dangling=true -q)
